FROM crpi-xhg6joi134vrkpzq.cn-shanghai.personal.cr.aliyuncs.com/vivienfanghua/amd-oneclick-base:rocm7.2.1-py3.12-v20260416

COPY git-wrapper /usr/local/bin/git
RUN chmod +x /usr/local/bin/git && /usr/local/bin/git --version
