FROM radeon-cloud-registry.cn-shanghai.cr.aliyuncs.com/admin/amd-oneclick-base:rocm7.2.1-py3.12-v20260416

COPY git-wrapper /usr/local/bin/git
RUN chmod +x /usr/local/bin/git && /usr/local/bin/git --version
