#!/usr/bin/env bash
set -u

REAL_GIT="${REAL_GIT:-/usr/bin/git}"
GH_PROXY_PREFIX="${GH_PROXY_PREFIX:-https://gh-proxy.org/}"

rewrite_github_url() {
    local url="$1"
    case "$url" in
        https://github.com/*|http://github.com/*)
            echo "${GH_PROXY_PREFIX}https://github.com/${url#*github.com/}"
            ;;
        git@github.com:*)
            echo "${GH_PROXY_PREFIX}https://github.com/${url#git@github.com:}"
            ;;
        *)
            echo "$url"
            ;;
    esac
}

fallback_github_url() {
    local url="$1"
    case "$url" in
        https://github.com/*|http://github.com/*)
            echo "http://github.com/${url#*github.com/}"
            ;;
        git@github.com:*)
            echo "http://github.com/${url#git@github.com:}"
            ;;
        *)
            echo "$url"
            ;;
    esac
}

is_github_url() {
    case "$1" in
        https://github.com/*|http://github.com/*|git@github.com:*) return 0 ;;
        *) return 1 ;;
    esac
}

if [[ "${1:-}" != "clone" ]]; then
    exec "$REAL_GIT" "$@"
fi

repo_index=-1
args=("$@")
i=1
while [[ "$i" -lt "${#args[@]}" ]]; do
    arg="${args[$i]}"
    if [[ "$arg" == "--" ]]; then
        if [[ $((i + 1)) -lt ${#args[@]} ]]; then
            repo_index=$((i + 1))
        fi
        break
    fi
    if [[ "$arg" == --*=* ]]; then
        ((i++))
        continue
    fi
    case "$arg" in
        -b|--branch|--config|-c|--depth|--filter|--jobs|-j|--origin|-o|--recurse-submodules|--reference|--reference-if-able|--server-option|--shallow-since|--shallow-exclude|--template|--upload-pack|-u)
            i=$((i + 2))
            continue
            ;;
        -*)
            ((i++))
            continue
            ;;
    esac
    repo_index="$i"
    break
done

if [[ "$repo_index" -lt 0 ]] || ! is_github_url "${args[$repo_index]}"; then
    exec "$REAL_GIT" "$@"
fi

original_url="${args[$repo_index]}"
proxy_url="$(rewrite_github_url "$original_url")"
fallback_url="$(fallback_github_url "$original_url")"

proxy_args=("${args[@]}")
proxy_args[$repo_index]="$proxy_url"
echo "[git-wrapper] cloning GitHub repo via gh-proxy.org" >&2
if "$REAL_GIT" "${proxy_args[@]}"; then
    exit 0
fi

fallback_args=("${args[@]}")
fallback_args[$repo_index]="$fallback_url"
echo "[git-wrapper] gh-proxy clone failed, retrying via http://github.com" >&2
exec "$REAL_GIT" "${fallback_args[@]}"
